### ISSUE TITLE
Finding usageId or /view/student_view

### ISSUE THREAD

**Issue by simultech** [edx-solutions/jquery-xblock#14]
I'm not sure if this is just documentation or something else, however when trying to run this with openEDx I get an issue with a 404 being triggered.  

The request is:
http://localhost:8000/courses/edX/DemoX/Demo_Course/xblock/i4x:;_;_edX;_DemoX;_vertical;_vertical_0270f6de40fc/view/student_view

And I get -> 404

However I run this (to make sure the URL is mostly right) -> Works:
http://localhost:8000/courses/edX/DemoX/Demo_Course/xblock/i4x:;_;_edX;_DemoX;_video;_0b9e39477cf34507a7a48f74be381fdd/handler/transcript/translation/en?videoId=b7xgknqkQk8

And when I run (to check the usageID)  -> 404 http://localhost:8000/courses/edX/DemoX/Demo_Course/xblock/i4x:;_;_edX;_DemoX;_vertical;_vertical_0270f6de40fcaTHISISINVALID/view/student_view

When I run (to check that the xblock is there) -> (django error Couldn't find handler u'view')
http://localhost:8000/courses/edX/DemoX/Demo_Course/xblock/i4x:;_;_edX;_DemoX;_vertical;_vertical_0270f6de40fc/handler/view/student_view

When I run (to check that the xblock is there) -> 404
http://localhost:8000/courses/edX/DemoX/Demo_Course/xblock/i4x:;_;_edX;_DemoX;_vertical;_vertical_0270f6de40fcTHISISINVALID/handler/view/student_view

So it looks like the usageID is correct, but I'm not sure whether its wrong in this context or whether its something to do with /view/student_view

I am using useCurrentHost if that is helpful.

**Comment by antoviaque** [comment]
You need a very recent edx-platform master, as this depends on this PR which has just been merged this week: https://github.com/edx/edx-platform/pull/2968

You also need to enable FEATURES['ENABLE_XBLOCK_VIEW_ENDPOINT'].

**Comment by simultech** [comment]
That was it, thank you so much
